name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Install goveralls and go coverage
        run: |
          go install github.com/mattn/goveralls@latest
          go get golang.org/x/tools/cmd/cover
      - name: Run Unit tests
        run: |
          go test -v -covermode=count -coverprofile=coverage.out
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github -repotoken ${{env.COVERALLS_TOKEN}}
